### ISSUE TITLE
Collection of getFusedLocationFlow and getRawLocationFlow not collect the location .

### ISSUE THREAD

**Issue by Office-Murtaza** [fcuringa/FreeLocationProvider#7]
val engineType = if (isFused) {
            FreeLocationProvider.Builder.EngineType.FUSED
        } else {
            FreeLocationProvider.Builder.EngineType.GPS_EXTRAPOLATION
        }
        freeLocationProvider = FreeLocationProvider.Builder(this.baseContext)
            .configure { provider ->
                provider.coroutineScope = lifecycleScope
                provider.coroutineDispatcher = Dispatchers.IO
                provider.engineType = engineType
                provider.sampleTimeLocationUpdateMs = 1000
                provider.maxLocationAccuracy = 20.0f
            }
            .build()
            
            
             private fun locationLocationManager() {
        if (isInternetConnected())
        lifecycleScope.launch {
            freeLocationProvider?.getRawLocationFlow()?.collect {
                providerCurrentLocationModel = it
                launchCurrentAddress(it)
            }
        }
        else
            alertToastShort(resources.getString(R.string.no_internet_connection_info))
    }

    private fun locationFusedObserver(){
        if (isInternetConnected())
        lifecycleScope.launch {
            freeLocationProvider!!.getFusedLocationFlow().catch {
                Log.e("TAG", "locationFusedObserver: ")
            }.collect {
                          providerCurrentLocationModel = it
                          launchCurrentAddress(it)

            }
        }
        else
            alertToastShort(resources.getString(R.string.no_internet_connection_info))

    }
    
    not collect the location model object even not move to inside collect .plz help me

**Comment by fcuringa** [comment]
Hi @Office-Murtaza, 

The use of the `FreeLocationProvider` as standalone - i.e. without the Mapbox integration requires that you setup the Location Service and Sensors yourself and then feed the location updates and sensor events to the provider with `feedLocation` and `feedSensor` respectively.

See an example here: https://github.com/fcuringa/FreeLocationProvider/blob/main/FreeLocationProviderMapbox/src/main/java/dev/pwar/freelocationprovidermapbox/FreeLocationProviderMapboxEngine.kt#L185

**Comment by fcuringa** [comment]
Closing this one then due to stale state.
